services:
  masonry-server:
    hostname: masonry-server
    container_name: masonry-server
    image: ghcr.io/smukherj1/expenses/masonry/server:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - masonry-backend
    environment:
      SPRING_PROFILES_ACTIVE: test
  masonry-db:
    hostname: masonry-db
    image: postgres:18.0-alpine3.22
    restart: unless-stopped
    container_name: masonry-db
    environment:
      POSTGRES_DB: masonry
      POSTGRES_USER: masonry
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - masonry-db_data:/var/lib/postgresql/data
    networks:
      - masonry-backend

volumes:
  masonry-db_data:

networks:
  masonry-backend:
    driver: bridge
