# Profile when running Sprint Boot App locally for development directly with the db running in a postgres container.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/masonry
    username: masonry
    password: password

# Override the values in application.yaml when running locally.
masonry:
  uploadsDir: data/uploads
  blobsDir: data/blobs