spring:
  grpc:
    server:
      port: 4000
  profiles:
    active: dev # Default profile for local development.
  application:
    name: server
  jpa:
    hibernate:
      ddl-auto: update

masonry:
  uploadsDir: ${MASONRY_UPLOADS_DIR}
  blobsDir: ${MASONRY_BLOBS_DIR}